# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-17 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
