# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_auto_20180612_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseendpoint',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Endpoint/Adverse outcome'),
        ),
    ]
