# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_animal_form_instructions_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter confidence factor name', max_length=45, unique=True)),
                ('description', models.TextField(blank=True)),
                ('increases_confidence', models.BooleanField(default=False, help_text='Check here if this factor INCREASES confidence in a study')),
                ('decreases_confidence', models.BooleanField(default=False, help_text='Check here if this factor DECREASES confidence in a study')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'confidence factors',
                'ordering': ('name',),
            },
        ),
    ]
