# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_confidencefactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('name', models.CharField(help_text='Enter confidence judgement name', max_length=45, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'confidence judgements',
                'ordering': ('value',),
            },
        ),
    ]
