# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_confidencejudgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
