# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_animal_form_instructions_updates'),
        ('assessment', '0019_assessment_cloned'),
    ]

    operations = [
    ]
