# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0005_add_bmds270'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='version',
            field=models.CharField(choices=[('BMDS231', 'BMDS v2.3.1'), ('BMDS240', 'BMDS v2.4.0'), ('BMDS260', 'BMDS v2.6.0'), ('BMDS2601', 'BMDS v2.6.0.1'), ('BMDS270', 'BMDS v2.7.0')], max_length=10),
        ),
    ]
