# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20170806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='coi_reported',
            field=models.PositiveSmallIntegerField(choices=[(4, '---'), (0, 'Authors report they have no COI'), (1, 'Authors disclosed COI'), (2, 'Unknown'), (3, 'Not reported')], default=4, help_text='Was a conflict of interest reported by the study authors?', verbose_name='COI reported'),
        ),
    ]
