# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20180405_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='ask_author',
            field=models.TextField(blank=True, help_text='Details on correspondence between data-extractor and author, if needed. Please include data and details of the correspondence. The files documenting the correspondence can also be added to HAWC as attachments and HERO as a new record, but first it is important to redact confidence or personal information (e.g., email address).', verbose_name='Correspondence details'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coi_details',
            field=models.TextField(blank=True, help_text='Details related to potential or disclosed conflict(s) of interest. When available, cut and paste the COI declaration with quotations. Provide details when a COI is inferred.', verbose_name='COI details'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coi_reported',
            field=models.PositiveSmallIntegerField(choices=[(4, '---'), (0, 'Authors report they have no COI'), (1, 'Authors disclosed COI'), (2, 'Not reported, but a COI is inferred based on author affiliation and/or funding source'), (3, 'Not reported')], default=4, help_text='Was a conflict of interest reported by the study authors?', verbose_name='COI reported'),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_author',
            field=models.BooleanField(default=False, help_text='Was the author contacted for clarification of methods, results, or to request additional data?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='full_citation',
            field=models.TextField(help_text='Complete study citation, in desired format. First author last name, Initial; Second author last name, Initial; etc. (Year). Title. Journal volume (issue): pages. Web link'),
        ),
        migrations.AlterField(
            model_name='study',
            name='funding_source',
            field=models.TextField(blank=True, help_text='When available, cut and paste the funding source information with quotations.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='published',
            field=models.BooleanField(default=False, help_text='If True, this study, study evaluation, and extraction details may be visible to reviewers and/or the public (if assessment-permissions allow this level of visibility). Team-members and project-management can view both published and unpublished studies.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='short_citation',
            field=models.CharField(help_text='How the study should be identified in HAWC (last name year, HERO ID). This field is used to select studies for figures and endpoint filters within HAWC, so you may need to add distinguishing features such as chemical name. This field is commonly used in HAWC visualizations.', max_length=256),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_identifier',
            field=models.CharField(blank=True, help_text='HERO LitCiter reference format {First author last name, year, HERO ID} *This field is used for HERO reference formatting purposes to help document preparation.', max_length=128, verbose_name='Internal study identifier'),
        ),
        migrations.AlterField(
            model_name='study',
            name='summary',
            field=models.TextField(blank=True, help_text='This field is often left blank, but used to add comments on data extraction, e.g., reference to full study reports or indicating which outcomes/endpoints in a study were not extracted.', verbose_name='Extraction comments'),
        ),
    ]
