# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-24 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_license_v2'),
        ('myuser', '0004_hawcuser_epa_sso_uid'),
    ]

    operations = [
    ]
