# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_auto_20170806_1721'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskofbias', '0015_auto_20170809_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBiasPerEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiasesperendpoint', to=settings.AUTH_USER_MODEL)),
                ('baseendpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiasesperendpoint', to='assessment.BaseEndpoint')),
            ],
            options={
                'verbose_name_plural': 'Risk of Biases per Endpoint',
                'ordering': ('final',),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasScorePerEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(10, 'Not reported'), (1, 'Critically deficient'), (2, 'Poor'), (3, 'Adequate'), (4, 'Good'), (0, 'Not applicable')], default=10)),
                ('notes', models.TextField(blank=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresperendpoint', to='riskofbias.RiskOfBiasMetric')),
                ('riskofbiasperendpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresperendpoint', to='riskofbias.RiskOfBiasPerEndpoint')),
            ],
            options={
                'ordering': ('metric', 'id'),
            },
        ),
        migrations.AddField(
            model_name='riskofbiasdomain',
            name='type',
            field=models.CharField(default='study', max_length=12),
        ),
    ]
