# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0015_auto_20170809_1125'),
        ('riskofbias', '0014_revise_rob_help_text'),
    ]

    operations = [
    ]
