# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0016_auto_20171026_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskofbiasassessment',
            old_name='number_of_reviewers',
            new_name='number_of_study_reviewers',
        ),
        migrations.AddField(
            model_name='riskofbiasassessment',
            name='number_of_endpoint_reviewers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
