# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0015_riskofbiasassessment_help_text'),
        ('riskofbias', '0016_merge_20171004_1254'),
    ]

    operations = [
    ]
