# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0019_auto_20171201_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskofbiasmetric',
            name='required_invitro',
            field=models.BooleanField(default=False, help_text='Is this metric required for in-vitro studies?', verbose_name='Required for in-vitro?'),
        ),
    ]
