# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0020_riskofbiasmetric_required_invitro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasmetric',
            name='required_invitro',
            field=models.BooleanField(default=True, help_text='Is this metric required for in-vitro studies?<br/><b>CAUTION:</b> Removing requirement will destroy all in-vitro responses previously entered for this metric.', verbose_name='Required for in-vitro?'),
        ),
    ]
