# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0021_auto_20180405_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasscore',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Not reported'), (1, 'Critically deficient'), (2, 'Deficient'), (3, 'Adequate'), (4, 'Good'), (0, 'Not applicable')], default=10),
        ),
    ]
