# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0024_auto_20180103_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskofbiasdomain',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
