# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0025_riskofbiasdomain_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskofbiasdomain',
            name='source',
        ),
        migrations.AddField(
            model_name='riskofbiasscore',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
