# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-02 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0026_auto_20180202_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_choice',
            field=models.TextField(default='Not reported'),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_score',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_symbol',
            field=models.TextField(default='NR'),
        ),
        migrations.AlterUniqueTogether(
            name='riskofbiasmetricanswers',
            unique_together=set([('metric', 'answer_choice', 'answer_symbol', 'answer_score', 'answer_order')]),
        ),
    ]
