# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0027_riskofbiasmetric_required_invitro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasdomain',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
