# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0028_riskofbiasscore_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskofbiasmetricanswers',
            options={'ordering': ('metric', 'order'), 'verbose_name_plural': 'Study Evaluation metric answers'},
        ),
        migrations.RenameField(
            model_name='riskofbiasmetricanswers',
            old_name='answer_choice',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='riskofbiasmetricanswers',
            old_name='answer_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='riskofbiasmetricanswers',
            old_name='answer_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='riskofbiasmetricanswers',
            old_name='answer_shade',
            new_name='shade',
        ),
        migrations.RenameField(
            model_name='riskofbiasmetricanswers',
            old_name='answer_symbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='riskofbiasscore',
            old_name='answers',
            new_name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='riskofbiasmetricanswers',
            unique_together=set([('metric', 'choice', 'symbol', 'score', 'order')]),
        ),
    ]
