# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0029_auto_20180326_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskofbiasanswersrecorded',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='riskofbiasanswersrecorded',
            name='riskofbias',
        ),
        migrations.RemoveField(
            model_name='riskofbiasscore',
            name='answer',
        ),
        migrations.DeleteModel(
            name='RiskOfBiasAnswersRecorded',
        ),
    ]
