# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0030_auto_20180402_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskofbiasmetricanswers',
            name='answer_score',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='riskofbias.RiskOfBiasScore'),
        ),
        migrations.AlterUniqueTogether(
            name='riskofbiasmetricanswers',
            unique_together=set([('score', 'metric', 'choice', 'symbol', 'answer_score', 'order')]),
        ),
    ]
