# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0031_auto_20180402_1248'),
        ('riskofbias', '0028_auto_20180410_1633'),
    ]

    operations = [
    ]
