# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0032_merge_20180411_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasscore',
            name='score',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
