# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-05 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_auto_20180719_0856'),
        ('riskofbias', '0033_auto_20180511_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBiasScorePerEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(10, 'Not reported'), (1, 'Critically deficient'), (2, 'Poor'), (3, 'Adequate'), (4, 'Good'), (0, 'Not applicable')], default=10)),
                ('notes', models.TextField(blank=True)),
                ('baseendpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiasesperendpoint', to='animal.Endpoint')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresperendpoint', to='riskofbias.RiskOfBiasMetric')),
                ('riskofbiasperendpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresperendpoint', to='riskofbias.RiskOfBias')),
            ],
            options={
                'ordering': ('metric', 'id'),
            },
        ),
    ]
