# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-07 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0023_auto_20171214_1256'),
        ('riskofbias', '0019_auto_20171107_1540'),
        ('riskofbias', '0033_auto_20180511_1250'),
    ]

    operations = [
    ]
