# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0034_merge_20191007_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='choice',
            field=models.TextField(default='Not reported'),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='riskofbias.RiskOfBiasScore'),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='symbol',
            field=models.TextField(default='NR'),
        ),
    ]
