# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-21 17:49
from __future__ import unicode_literals

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0011_auto_20180612_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='full_text_url',
            field=utils.models.CustomURLField(blank=True, help_text='Link to full-text URL from journal site (may require increased access privileges to view)'),
        ),
    ]
