# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0012_result_resulttags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='diagnostic',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not reported'), (1, 'medical professional or test'), (2, 'medical records'), (3, 'self-reported'), (4, 'questionnaire'), (5, 'hospital admission'), (7, 'registry'), (6, 'other')]),
        ),
    ]
