# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0013_auto_20180403_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='dose_response',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A, single dose level study'), (1, 'N/A, no effects detected'), (2, 'yes, visual appearance of monotonicity but no trend'), (3, 'yes, monotonic and significant trend'), (4, 'yes, visual appearance of non-monotonic but no trend'), (5, 'yes, non-monotonic and significant trend'), (6, 'no pattern'), (7, 'unclear'), (8, 'not-reported')], default=0, help_text='Was a trend observed?', verbose_name='Dose Response Trend'),
        ),
    ]
