# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0015_auto_20180921_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='metric',
            field=models.CharField(help_text="In what was the chemical measured? Ex. Air; Maternal serum<span class='help-text-notes'>Exposure medium (ex. air, water), tissue or bodily fluid in which biomarker detected (ex. blood, serum, plasma, urine, feces, breast milk, hair, saliva, teeth, finger or toe nails), or occupation from which exposure assumed (cadmium factory worker)</span><span class='important-note'>This field is commonly used in HAWC visualizations</span>", max_length=128, verbose_name='Measurement metric'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='metric_description',
            field=models.TextField(help_text="Briefly describe how chemical levels in measurement metric were assessed. Ex. Single plasma sample collected for each pregnant woman during the first trimester<span class='help-text-notes'>Note key details or if measurement details not provided. May vary by assessment.</span>", verbose_name='Measurement description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='ci_units',
            field=models.FloatField(blank=True, default=0.95, help_text='Write as a decimal: a 95% CI should be recorded as 0.95. Ex. 0.95', null=True, verbose_name='Confidence interval (CI)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='dose_response',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A, single dose level study'), (1, 'N/A, no effects detected'), (2, 'yes, visual appearance of monotonicity but no trend'), (3, 'yes, monotonic and significant trend'), (4, 'yes, visual appearance of non-monotonic but no trend'), (5, 'yes, non-monotonic and significant trend'), (6, 'no pattern'), (7, 'unclear'), (8, 'not-reported')], default=0, help_text="<span class='help-text-notes optional'>Optional</span>", verbose_name='Dose response trend'),
        ),
    ]
