# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-21 19:48
# Customized by tfeiler, to split into 3, controlling the order, and adding data migration
#
# run via:
#   python manage.py migrate
# reverse (to previous migration) with something like:
#   python manage.py migrate epi 0016_animal_form_instructions_updates

from __future__ import unicode_literals
from pprint import pprint

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0017_multiple_exposure_cts_b')
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='estimate_type',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='lower_ci',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='lower_range',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='upper_ci',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='upper_range',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='variance',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='variance_type',
        ),
    ]
