# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_optional_captions'),
        ('summary', '0013_auto_20170806_1721'),
    ]

    operations = [
    ]
