# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-03 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_confidencefactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0014_visual_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of this evidence profile table (spaces and special-characters allowed).', max_length=128)),
                ('slug', models.SlugField(help_text='The URL (web address) used to describe this object (no spaces or special-characters).', verbose_name='URL Name')),
                ('settings', models.TextField(default='undefined', help_text='Paste content from a settings file from a different evidence profile, or keep set to "undefined".')),
                ('caption', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
                ('hawcUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence profiles',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceProfileScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(help_text='This must be one of the available "outcome" values listed in the parent envidence profile stream', max_length=128)),
                ('scenario_name', models.CharField(max_length=128)),
                ('studies', models.TextField(default='{}')),
                ('confidencefactors_increase', models.TextField(default='[]')),
                ('confidencefactors_decrease', models.TextField(default='[]')),
                ('summary_of_findings', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'stream scenarios',
                'ordering': ('outcome', 'scenario_name'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceProfileStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_title', models.CharField(help_text='Enter the title of this profile streaam (spaces and special-characters allowed).', max_length=128)),
                ('confidence_judgement', models.TextField(default='{}')),
                ('outcomes', models.TextField(default='[]')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('evidenceprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='summary.EvidenceProfile')),
            ],
            options={
                'verbose_name_plural': 'profile streams',
                'ordering': ('stream_title',),
            },
        ),
        migrations.AddField(
            model_name='evidenceprofilescenario',
            name='evidenceprofilestream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='summary.EvidenceProfileStream'),
        ),
    ]
