# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_merge_20171012_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='sort_order',
            field=models.CharField(choices=[('short_citation', 'Short Citation'), ('overall_confidence', 'Final Study Confidence')], default='short_citation', max_length=40),
        ),
        migrations.AlterField(
            model_name='datapivot',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
