# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_auto_20180514_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapivot',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visual',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
