# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_auto_20180531_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceprofile',
            old_name='cross_stream_conclusions',
            new_name='cross_stream_confidence_judgement',
        ),
        migrations.RemoveField(
            model_name='evidenceprofilescenario',
            name='summary_of_findings',
        ),
        migrations.RemoveField(
            model_name='evidenceprofilestream',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='evidenceprofile',
            name='cross_stream_inferences',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='evidenceprofile',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidenceprofilescenario',
            name='outcome',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='evidenceprofilescenario',
            name='studies',
            field=models.TextField(default='[]'),
        ),
    ]
