# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-09 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0018_auto_20180719_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenceprofile',
            name='settings',
        ),
    ]
