# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-25 22:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0019_remove_evidenceprofile_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceProfileScenario_JSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('outcome', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('scenario_name', models.CharField(blank=True, help_text='(optional) If a stream only has one scenario, there is no reason to give it a name', max_length=128)),
                ('studies', django.contrib.postgres.fields.jsonb.JSONField(default='[]')),
                ('confidencefactors_increase', django.contrib.postgres.fields.jsonb.JSONField(default='[]')),
                ('confidencefactors_decrease', django.contrib.postgres.fields.jsonb.JSONField(default='[]')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('evidenceprofilestream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_jsonb', to='summary.EvidenceProfileStream')),
                ('hawcuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stream scenarios',
                'ordering': ('scenario_name',),
            },
        ),
    ]
