# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-20 13:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0019_remove_evidenceprofile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceprofilescenario',
            name='summary_of_findings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='evidenceprofilestream',
            name='summary_of_findings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
