# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0020_datapivotupload_worksheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapivotupload',
            name='excel_file',
            field=models.FileField(help_text='Upload an Excel file in XLSX format.', max_length=250, upload_to='data_pivot_excel', verbose_name='Excel file'),
        ),
    ]
