# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-05 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0021_evidenceprofile_one_scenario_per_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceprofile',
            name='one_scenario_per_stream',
            field=models.BooleanField(default=False, help_text='If checked, this evidence profile table wlll only have one outcome scenario per profile stream', verbose_name='Only One Scenario per Stream?'),
        ),
    ]
