# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-06 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0021_auto_20181128_1124'),
        ('summary', '0021_evidenceprofile_one_scenario_per_stream'),
    ]

    operations = [
    ]
