# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0023_auto_20181224_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceprofile',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_profiles', to='assessment.Assessment'),
        ),
    ]
