# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0024_auto_20190206_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visual',
            name='dose_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='assessment.DoseUnits'),
        ),
    ]
