# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_auto_20170806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgroup',
            name='comments',
            field=models.TextField(blank=True, help_text='Any addition notes for this animal-group.', verbose_name='Animal Husbandry'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='LOEL',
            field=models.SmallIntegerField(default=-999, help_text='Lowest observed effect level', verbose_name='LOAEL'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='NOEL',
            field=models.SmallIntegerField(default=-999, help_text='No observed effect level', verbose_name='NOAEL'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, help_text='Text-description of the experimental protocol used. May also include information such as animal husbandry. Note that dosing-regime information and animal details are captured in other fields.', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='litter_effects',
            field=models.CharField(choices=[('NA', 'Not-applicable'), ('NR', 'Not-reported'), ('YS', 'Yes, statistical control'), ('YD', 'Yes, study-design'), ('N', 'No'), ('O', 'Other')], default='NA', help_text='Type of controls used for litter-effects', max_length=2),
        ),
    ]
