# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_auto_20170806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.CharField(choices=[('1r', '1-generation reproductive'), ('2r', '2-generation reproductive'), ('Ac', 'Acute (<24 hr)'), ('St', 'Short-term (1-30 days)'), ('Sb', 'Subchronic (30-90 days)'), ('Ch', 'Chronic (>90 days)'), ('Ca', 'Cancer'), ('Me', 'Mechanistic'), ('Rp', 'Reproductive'), ('Dv', 'Developmental'), ('Ot', 'Other'), ('NR', 'Not-reported')], help_text='Type of study being performed; be as specific as-possible', max_length=2),
        ),
    ]
