# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_auto_20180403_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='cas',
            field=models.CharField(blank=True, help_text='CAS number for chemical-tested. Use N/A if not applicable', max_length=40, verbose_name='Chemical identifier (CAS)'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='chemical',
            field=models.CharField(blank=True, help_text='This field may get displayed in visualizations, so consider using a common acronym, e.g., BPA instead of Bisphenol A', max_length=128, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, help_text='Add additional comments. In most cases, this field will be blank. Note that dosing-regime information and animal details are captured in the Animal Group extraction module.', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='diet',
            field=models.TextField(blank=True, help_text='Description of animal-feed (use diet as described in methods)'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='guideline_compliance',
            field=models.CharField(blank=True, help_text='Description of any compliance methods used (i.e. use of EPA \n                    OECD, NTP, or other guidelines; conducted under GLP guideline \n                    conditions, non-GLP but consistent with guideline study, \n                    etc.). This field response should match any description used \n                    in study evaluation in the reporting quality domain.', max_length=128),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(help_text='Short-text used to describe the experiment (i.e. 2-Year Cancer Bioassay, 10-Day Oral, 28-Day Inhalation, etc.) using title style (all words capitalized). If study contains more than one chemical, then also include the chemical name (e.g. 28-Day Oral PFBS).', max_length=80),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.CharField(choices=[('Ac', 'Acute (<24 hr)'), ('St', 'Short-term (1-30 days)'), ('Sb', 'Subchronic (30-90 days)'), ('Ch', 'Chronic (>90 days)'), ('Ca', 'Cancer'), ('Me', 'Mechanistic'), ('Rp', 'Reproductive'), ('1r', '1-generation reproductive'), ('2r', '2-generation reproductive'), ('Dv', 'Developmental'), ('Ot', 'Other'), ('NR', 'Not-reported')], help_text='Type of study being performed; be as specific as possible', max_length=2),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='vehicle',
            field=models.CharField(blank=True, help_text='Describe vehicle (use name as described in methods but also add the common name if the vehicle was described in a non-standard way)', max_length=64, verbose_name='Chemical vehicle'),
        ),
    ]
