# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0022_auto_20180725_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgroup',
            name='animal_source',
            field=models.CharField(blank=True, help_text='Source from where animals were acquired', max_length=128),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='comments',
            field=models.TextField(blank=True, help_text='Copy paste animal husbandry information from materials and methods, use quotation marks around all text directly copy/pasted from paper.', verbose_name='Animal Husbandry'),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='duration_observation',
            field=models.FloatField(blank=True, help_text='Numeric length of time between start of exposure and outcome assessment, in days when &lt;7 (e.g., 5 days), weeks when &ge;7 days to 12 weeks (e.g., 1 week, 12 weeks), or months when &gt;12 weeks (e.g., 15 months). For repeated measures use descriptions such as "1, 2 and 3 weeks"', null=True, verbose_name='Exposure-outcome duration'),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='lifestage_exposed',
            field=models.CharField(blank=True, help_text='Definitions: <strong>Developmental</strong>: Prenatal and perinatal exposure in dams or postnatal exposure in offspring until sexual maturity (~6 weeks in rats and mice). Include studies with pre-mating exposure <em>if the endpoint focus is developmental</em>. <strong>Adult</strong>: Exposure in sexually mature males or females. <strong>Adult (gestation)</strong>: Exposure in dams duringpregnancy. <strong>Multi-lifestage</strong>: includes both developmental and adult (i.e., multi-generational studies, exposure that start before sexual maturity and continue to adulthood)', max_length=32, verbose_name='Exposure lifestage'),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='name',
            field=models.CharField(help_text='Name should be: sex, common strain name, species and use Title Style (e.g. Male Sprague Dawley Rat, Female C57BL/6 Mice). For developmental studies, include the generation before sex in title (e.g., F1 Male Sprague Dawley Rat or P0 Female C57 Mice)', max_length=80),
        ),
    ]
