# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0025_animal_diet_field_relocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgroup',
            name='name',
            field=models.CharField(help_text='\n            Name should be: sex, common strain name, species (plural) and use Title Style \n            (e.g. Male Sprague Dawley Rat, Female C57BL/6 Mice, Male and Female \n            C57BL/6 Mice). For developmental studies, include the generation before \n            sex in title (e.g., F1 Male Sprague Dawley Rat or P0 Female C57 Mice)\n            ', max_length=80),
        ),
        migrations.AlterField(
            model_name='dosingregime',
            name='duration_exposure',
            field=models.FloatField(blank=True, help_text='Length of exposure period (fractions allowed), used for sorting in visualizations. For single-dose or multiple-dose/same day gavage studies, 1.', null=True, verbose_name='Exposure duration (days)'),
        ),
        migrations.AlterField(
            model_name='dosingregime',
            name='duration_exposure_text',
            field=models.CharField(blank=True, help_text='Length of time between start of exposure and outcome assessment, in days when &lt;7 (e.g., 5d), weeks when &ge;7 days to 12 weeks (e.g., 1wk, 12wk), or months when &gt;12 weeks (e.g., 15mon). For repeated measures use descriptions such as "1, 2 and 3 wk".  For inhalations studies, also include hours per day and days per week, e.g., "13wk (6h/d, 7d/wk)." This field is commonly used in visualizations, so use abbreviations (h, d, wk, mon, y) and no spaces between numbers to save space. For reproductive and developmental studies, where possible instead include abbreviated age descriptions such as "GD1-10" or "GD2-PND10". For gavage studies, include the number of doses, e.g. "1wk (1dose/d, 5d/wk)" or "2doses" for a single-day experiment.', max_length=128, verbose_name='Exposure duration (text)'),
        ),
    ]
