# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0029_ani_experiment_multigen_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='observation_time_text',
            field=models.CharField(blank=True, help_text='Text for reported observation time (ex: "60-90 PND", 5d, 2wk)', max_length=64),
        ),
    ]
