# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0029_ani_experiment_multigen_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='assay_type',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
