# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-06 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_auto_20180719_0856'),
        ('animal', '0029_ani_experiment_multigen_field'),
    ]

    operations = [
    ]
